[project]
name = "flux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "numpy>=2.3.4",
    "requests>=2.32.5",
    "sortedcontainers>=2.4.0",
    "websockets>=15.0.1",
]
